# Generated by Django 6.0.6 on 2026-06-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_Id', models.IntegerField(null=True)),
                ('emp_name', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('emp_picture', models.ImageField(null=True, upload_to='Employee_picture')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
